# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CodeCheck For Develop

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Show Maven Version
        run: |
          java -version
          mvn -version

      - uses: actions/checkout@v2
      - name: Set up JDK 1.6
        uses: actions/setup-java@v1
        with:
          java-version: 1.6

      - name: Build DongTai-Java-Agent With Maven
        run: |
          mvn -version
          mvn -B package -Dmaven.test.skip=true
