# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CodeCheck For Develop

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.6
        uses: actions/setup-java@v1
        with:
          java-version: 1.6

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.2.5

      - name: Solve Maven Effective Settings
        run: |
          mkdir -p ~/.m2/repository/
          cp deploy/settings.xml ~/.m2/repository/
          cd /tmp/
          mvn help:effective-settings

      - name: Build DongTai-Java-Agent With Maven
        run: |
          mvn -B package -Dmaven.test.skip=true
