# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: DongTai Agent Java CodeCheck、Unit Test And Vulns Test

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
            
      - uses: dbelyaev/action-checkstyle@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.2.5

      - name: Build DongTai-Java-Agent With Maven
        run: |
          mvn -version
          mvn -B package -Dmaven.test.skip=true
      
      - uses: mirromutth/mysql-action@v1.1
        with:
          character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
          collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
          mysql version: '8.0' # Optional, default value is "latest". The version of the MySQL
          mysql database: 'test' # Optional, default value is "test". The specified database which will be create
          mysql root password: test # Required if "mysql user" is empty, default is empty. The root superuser password
          mysql user: 'test' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
          mysql password: test # Required if "mysql user" exists. The password for the "mysql user"
      
      - name: OpenRASP-Vulns-Test
        run: |
          cd ..

          echo "download apache-tomcat-8.5.0..."
          wget https://github.com/exexute/github_action_samples/releases/download/1.0.0/apache-tomcat-8.5.40.zip 1>/dev/null
          unzip apache-tomcat-8.5.40.zip

          echo "copy dongtai agent java to tomcat..."
          cp DongTai-agent-java/release/iast-agent.jar apache-tomcat-8.5.40/iast/agent.jar
          cp DongTai-agent-java/release/lib/iast-core.jar apache-tomcat-8.5.40/temp/iast-core.jar
          cp DongTai-agent-java/release/lib/iast-inject.jar apache-tomcat-8.5.40/temp/iast-inject.jar
          cd apache-tomcat-8.5.40
          
          echo "init mysql..."
          #./init.sh
          mysql -V
          
          echo "start catalina and waitting 30s..."
          ./bin/startup.sh 2>/dev/null
          sleep 30

          echo "start vulns spider..."
          ./spider.sh

          echo "waitting for send vuls data"
          sleep 600
      
      - name: Benchmark-Vulns-Test
        run: |
          pwd
          ls -l
          java -version
          mvn -version
          # download Benchmark
          # Copy Agent To Benchmark
          # Run
