name: Maven Package

on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.6
        uses: actions/setup-java@v2
        with:
          java-version: '1.6'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean -B package --file pom.xml

#      - name: Publish to GitHub Packages Apache Maven
#        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
#        env:
#          GITHUB_TOKEN: ${{ github.token }}
